name: ci

on:
  push:
    branches:
      - '*'

jobs:
  ci:
    strategy:
      matrix:
        php-versions: [ '8.1' ]
        composer-versions: ['--prefer-dist', '--prefer-lowest']

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Set composer dependencies
        run: composer update ${{ matrix.composer-versions }}

      - name: Run tests
        run: composer test